In [ ]:
# Numpy --> Numerical Python
import numpy as np
print(np.__version__)

2.0.2


In [ ]:
# numpy provides the support for most powerful data structure -- array
arr = np.array([10,20,30,40,50,60])
print(arr)
print(type(arr))

[10 20 30 40 50 60]
<class 'numpy.ndarray'>


In [ ]:
# Python List vs Numpy

# how much execution time will be taken by List and sum()
import time
numbers = list(range(1,100000001))
total = 0
start_time = time.time()  # record start time
for i in numbers:
  total = total + i
end_time = time.time()  # record end time
print("Total : ",total)
print("Execution Time : ",end_time - start_time,"seconds")
print(f"Execution Time : {end_time - start_time:.4f} seconds")
#.4f means show 4 digits after the decimal point

Total :  5000000050000000
Execution Time :  16.85479187965393 seconds
Execution Time : 16.8548 seconds


In [ ]:
numbers = np.arange(1,100000001)
total = 0
start_time = time.time()  # record start time
total = np.sum(numbers)
end_time = time.time()  # record end time
print("Total : ",total)
print("Execution Time : ",end_time - start_time,"seconds")
print(f"Execution Time : {end_time - start_time:.4f} seconds")

Total :  5000000050000000
Execution Time :  0.06901049613952637 seconds
Execution Time : 0.0690 seconds


In [ ]:
# array()
# In programming , an array is a data structure used to store collection of data values

# Array : Single Dimension (1D) and Multi Dimensional (2D)

# How to create an array (1D)
arr = np.array([10,20,30,40,50,60])
print(type(arr))
print(arr)

<class 'numpy.ndarray'>
[10 20 30 40 50 60]


In [ ]:
# An array is a collection of Similar Data Type
emp_info = np.array([123 , "Yash" , 89.31 , True])
print(emp_info)

['123' 'Yash' '89.31' 'True']


In [ ]:
# shape property
# used to determine the dimensions of an array
# For 1D array return (n,) --> where n is the number of elements
# For 2D array return (n,m) --> where n is the number of rows and m is the number of columns

arr = np.array([10,20,30,40,50,60])
print(arr.shape)

(6,)


In [ ]:
# 2D Array
arr = np.array([[1,2,3],[3,4,5],[5,6,7]])
print(arr.shape)
print(arr)

# Tip for 2D Array
# np.array([])
# 3x3 matrix

# Create a 2X5 Matrix
# Create a 4X3 Matrix

(3, 3)
[[1 2 3]
 [3 4 5]
 [5 6 7]]


In [ ]:
# Indexing And Slicing
arr = np.array([10,20,30,40,50,60])

# 10  20   30    40    50    60
# 0   1     2    3     4     5
# -6  -5    -4   -3    -2    -1

print(arr)
print(arr[-1])
print(arr[3])
print(arr[1:5])
print(arr[::-1])

[10 20 30 40 50 60]
60
40
[20 30 40 50]
[60 50 40 30 20 10]


In [ ]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)
print(arr[1,1])  # show me the element which exist at r1 and c1
print(arr[2,2])

# show me the first row only
print(arr[0])

# show me the second column only    FOR COLUMNS USE THIS SYNTAX [:,COLUMN_INDEX_NUMBER]
print(arr[:,1])
print(arr[:,2])

print(arr[2])

# show only first 2 rows
print(arr[0:2])   # ROW 0 AND ROW 1

print(arr[:,1:])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
5
9
[1 2 3]
[2 5 8]
[3 6 9]
[7 8 9]
[[1 2 3]
 [4 5 6]]
[[2 3]
 [5 6]
 [8 9]]


In [ ]:
# Numpy Data Types
arr = np.array([10,20,30,40])
print(arr.dtype)
# dtype property helps us to determine the data type of an Array

int64


In [ ]:
arr = np.array([10.1,20.2,30.3,40.4])
print(arr.dtype)

float64


In [ ]:
arr = np.array([True,False,False,True])
print(arr.dtype)

bool


In [ ]:
arr = np.array(['A','B','C','D'])
print(arr.dtype)
# u = unicode string
# sama je macam str tapi dalam numpy nama dia u
# U1 tu merujuk pada setiap satu tu dalam dia ada 1 je

<U1


In [ ]:
arr = np.array(['Python','Nexperts Academy','C','D'])
print(arr.dtype)
#U16 maksudnya max number of character ada 16
# kira ada berapa banyak huruf

<U16


In [ ]:
# we can also use dtype for Conversion
arr = np.array([10,20,30,40])
print(arr.dtype)
print(arr.nbytes) # total bytes used by an array

# this int64 means 64 Bits
# meaning each and every individual element of an array can take upto 64 bits
# we have 4 elements
# 4 * 64 Bits --> Total Size Of Arr : 256 bits
# and if we convert it into bytes  4 element * 8 bytes  : 32 bytes


# behind the scene each and every individual element will gonna take 64 digits space

# 6bits 6*4 ==> 24 bits
#  Total Size Of Arr :24 bits

int64
32


In [ ]:
arr = np.array([10,20,30,40],dtype='i1')
print(arr.dtype)
print(arr.nbytes)

# this int8 means 8 Bits
# meaning each and every individual element of an array can take upto 8 bits
# we have 4 elements
# 4 * 8 Bits --> Total Size Of Arr : 32 bits
# and if we convert it into bytes  4 element * 1 bytes  : 4 bytes

# behind the scene each and every individual element will gonna take 8 digits space


# when in an array you are storing the age or marks

int8
4


In [ ]:
age = np.array([34,78,56,21,90,100,120,17])
print(age.dtype)
print(age.nbytes)

int64
64


In [ ]:
age = np.array([34,78,56,21,90,100,120,17],dtype='i1')
print(age.dtype)
print(age.nbytes)

int8
8


In [ ]:
age = np.array([34,78,56,21,90,100,120,17],dtype='i4')
print(age.dtype)
print(age.nbytes)

# i1 --> 8 digits space
# i2 --> 16 digits space
# i4 --> 32 digits space
# i8 --> 64 digits space

int32
32


In [ ]:
a = np.array([10,20,30,40,50],dtype='f')
print(a)
print(a.dtype)

[10. 20. 30. 40. 50.]
float32


In [ ]:
a = np.array([10. ,20. ,30. ,40., 50.],dtype='i')
print(a)
print(a.dtype)

[10 20 30 40 50]
int32


In [ ]:
# astype() used for conversions
arr = np.array([10. ,20. ,30. ,40., 50.])
arr = arr.astype('i8')
print(arr.dtype)

int64


In [ ]:
# copy() vs view() methods of Numpy

# copy()
# a copy will create a new independent array in a different memory location

org_array = np.array([1,2,3,4,5,6])
print(org_array)

copied_arr = org_array.copy()
print(copied_arr)

# if we make any changes in copied array , it won't effect the original array
copied_arr[0] = 100
print(copied_arr)
print(org_array)

[1 2 3 4 5 6]
[1 2 3 4 5 6]
[100   2   3   4   5   6]
[1 2 3 4 5 6]


In [ ]:
#cubaan pertama copy saya
org_array = np.array([10,20,30])
copied_arr = org_array.copy()
print(copied_arr)

copied_arr[0] = 25
print(org_array)

[10 20 30]
[10 20 30]


In [ ]:
# view()
# a view is the representation of the original array
# once changes made, developer will get notified

org_array = np.array([1,2,3,4,5,6])
print(org_array)

copied_arr = org_array.view()
print(copied_arr)

# if we make any changes in copied array , it will effect the original array
copied_arr[0] = 100
print(copied_arr)
print(org_array)

# if we make any changes in org array , it will effect the copied array
org_array[4] = 400
print(org_array)
print(copied_arr)

[1 2 3 4 5 6]
[1 2 3 4 5 6]
[100   2   3   4   5   6]
[100   2   3   4   5   6]
[100   2   3   4 400   6]
[100   2   3   4 400   6]


In [ ]:
org_array = np.array([1,2,3,4,5,6])
copied_arr = org_array.view()

# if use view, both will same shares_memory() --> will return True if arrays are sharing the same memory location

# syntax to see if its true
print(np.shares_memory(org_array,copied_arr))

True


In [ ]:
# Numpy Array Reshaping
# Converting 1D into 2D or Converting 2D into 1D
# name of the method: reshape()

arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
# ini masih 1D matrix
print(arr.shape)  # 2x6  3x4  4x3  6x2  12x1  1x12
# berapa darab berapa jawapan dia 12 sebab character dia max ada 12

# kalau nak tukar kepada 3 by 4 matrix cara tulis dia macam ni
arr = arr.reshape(3,4)
print(arr)
print(arr.shape)

(12,)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)


In [ ]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13])
print(arr.shape)  # 13x1  1x13 ini 1D dimension
arr = arr.reshape(13,1) # ini kita nak reshape dia jadi 2D matrix
print(arr.shape)
print(arr)

(13,)
(13, 1)
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]]


In [ ]:
# numpy.newaxis is used to increase the dimension of the existing array by one more dimension
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13])
# arr[:,np.newaxis]            Column Vector
arr = arr[np.newaxis,:]      # Row Vector
print(arr.shape)

(1, 13)


In [ ]:
# Converting 2D into 1D

twod = np.array([[1,2],[3,4],[5,6]])
print(twod.shape)# akan tunjuk matrix dia berapa
arr = twod.reshape(6)
print(arr)

(3, 2)
[1 2 3 4 5 6]


In [ ]:
twod = np.array([[1,2],[3,4],[5,6]])
print(twod.shape)
arr = twod.reshape(-1)
print(arr) # second method untuk convert 2D to 1D

(3, 2)
[1 2 3 4 5 6]


In [ ]:
twod = np.array([[1,2],[3,4],[5,6]])
print(twod.shape)
arr = twod.flatten()
print(arr) # third method untuk convert 2D to 1D

(3, 2)
[1 2 3 4 5 6]


In [ ]:
# concatenate()
# used to join 2 arrays
# METHOD NOT SO IMPORTANT BUT SOMETIMES CAN BE USEFUL
# arr merupakan array
# array tu macam list tapi dalam numpy panggil arr
# concatenate method gabungkan 2 arr
# tapi cuma boleh gabung kalau dua dua ni sama DIMENSI

pp1 = np.array([20,60,80,45,32])
pp2 = np.array([10,20,30,40,50,67,32,90])
pp3 = np.array([100,200,300,400])
arr = np.concatenate((pp1,pp2,pp3))
print(arr)

[ 20  60  80  45  32  10  20  30  40  50  67  32  90 100 200 300 400]


In [ ]:
# ini contoh lain tapi ni untuk 2D
# cara kita nak concatenate, perhatikan syntax berbeza dekat bracket
t1 = np.array([[1,2],[3,4]])
t2 = np.array([[5,6],[7,8],[9,10]])
arr = np.concatenate((t1,t2))
print(arr)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [ ]:
# cubaan saya concatenate arr
test1 = np.array([1,2,3,4,5])
test2 = np.array([6,7,8,9,10])
arr = np.concatenate((test1,test2))
print(arr)
# yeay jadi, kena ada square bracket dekat dalam syntax

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
# next method:
# array_split()
# split method tu kita split array yang panjang tu jadi berapa yang kita nak

arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])
arr = np.array_split(arr,3)
print(arr[0])
print(arr[1])
print(arr[2])

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]


In [ ]:
# Sorting
# np.sort() by default it will sort in an ascending order

prices = np.array([78,34,56,90,102,34,12,67,172,120,95,45])
print(np.sort(prices))

[ 12  34  34  45  56  67  78  90  95 102 120 172]


In [ ]:
# sorting untuk descending order
prices = np.array([78,34,56,90,102,34,12,67,172,120,95,45])
print(np.sort(prices)[::-1]) # descending order
# syntax ::-1 will become reverse or descending order

[172 120 102  95  90  78  67  56  45  34  34  12]


In [ ]:
# Filter and Searching In An Array
# dekat sini kita guna for loop
prices = np.array([78,34,56,90,102,34,12,67,172,120,95,45])
print(prices)

for i in prices:
  if i>=50:
    print(i)

[ 78  34  56  90 102  34  12  67 172 120  95  45]
78
56
90
102
67
172
120
95


In [ ]:
# second method untuk filter and search
# Boleh guna Boolean Masking
prices = np.array([78,34,56,90,102,34,12,67,172,120,95,45])
prices>=50

array([ True, False,  True,  True,  True, False, False,  True,  True,
        True,  True, False])

In [ ]:
prices = np.array([78,34,56,90,102,34,12,67,172,120,95,45])
# Boolean Masking
newarr = prices[prices>=50]  # here we are applying a filter prices[showMeOnlyTrueValues]
print(newarr)

[ 78  56  90 102  67 172 120  95]


In [ ]:
prices = np.array([78,34,56,90,102,34,12,67,172,120,95,45])
# show the even number prices
newarr = prices[prices%2==0]
print(newarr)

[ 78  34  56  90 102  34  12 172 120]


In [ ]:
# np.where(expression)
prices = np.array([78,34,56,90,102,34,12,67,172,120,95,45])
# np.where returns INDEX NUMBERS
res = np.where(prices%2==0)
print(prices[res])

[ 78  34  56  90 102  34  12 172 120]


In [ ]:
prices = np.array([78,34,56,90,102,34,12,67,172,120,95,45])
res = np.where((prices%2==0) & (prices>=50))
print(prices[res])

# & combines both conditions

[ 78  56  90 102 172 120]


In [ ]:
prices = np.array([78,34,56,90,102,34,12,67,172,120,95,45])
print(prices[(prices%2==0) & (prices>=50)])

[ 78  56  90 102 172 120]


In [ ]:
# SALARY CLASSIFICATION
salary = np.array([25000, 40000, 55000, 70000, 30000, 90000])
# Replace salary with High if salary >= 60000
# Replace salary with Medium if salary >= 40000 and <= 60000
# Otherwise Low

# syntax:
# np.where(condition,value_if_true,value_if_false)

result = np.where(
    salary >= 60000 , "High" ,
    np.where(salary >=40000 , "Medium" ,"Low")
)

print(result)

['Low' 'Medium' 'Medium' 'High' 'Low' 'High']


In [ ]:
# Numpy Random Module
from numpy import random
x = random.randint(100)  # 1 till 100
print(x)

35


In [ ]:
x = random.randint(100,150)  # 100 till 150
print(x)

117


In [ ]:
# rand() generate random float
# method returns a random float value between 0 and 1

print(random.rand())

0.8412362562876106


In [ ]:
# generating 1D Array
arr = random.randint(30,120,size=(5)) # size means dimensions of an array
print(arr)

[42 90 39 75 37]


In [ ]:
# generating 2D Array
arr = random.randint(30,120,size=(3,4)) # size means dimensions of an array
print(arr)

[[ 86  68  45  31]
 [ 56  44  74 103]
 [ 78  70 112 116]]


In [ ]:
arr = random.rand(10)
print(arr)

[0.70264147 0.28043249 0.8712521  0.87385699 0.1929973  0.11086911
 0.66597321 0.27798371 0.06867217 0.47354895]


In [ ]:
arr = random.rand(5,4)
print(arr)

[[0.65958391 0.40995572 0.21210733 0.31155359]
 [0.20526765 0.29585377 0.52618273 0.87331864]
 [0.46562927 0.7559677  0.12602561 0.88726676]
 [0.19360962 0.80871213 0.82790252 0.07547583]
 [0.47533512 0.53410317 0.28391454 0.03028464]]


In [ ]:
# choice() method allows you to generate a random value
# based on an array of values

arr = random.choice([10,20,30,40,50,60])
print(arr)

30


In [ ]:
arr = random.choice([10,20,30,40,50,60],size=(7))
print(arr)

[60 50 50 20 40 50 60]


In [ ]:
arr = random.choice([10,20,30,40,50,60],size=(3,4))
print(arr)

[[50 10 20 50]
 [40 60 60 20]
 [50 50 60 40]]


In [ ]:
# numpy.zeros()
# this function allows us to create an array filled with Zeros
# default data type will be Float

x = np.zeros(7)
print(x)

[0. 0. 0. 0. 0. 0. 0.]


In [ ]:
x = np.zeros((3,3),dtype='i')
print(x)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [ ]:
# numpy.ones()
# this function allows us to create an array filled with Ones
# default data type will be Float

x = np.ones(7)
print(x)

[1. 1. 1. 1. 1. 1. 1.]


In [ ]:
# numpy.sum()
# used to compute the sum of all elements

x = np.random.randint(50,size=(120))
print(x)

[20 48 35 41 40 25 25  8  2  5 39 17 31  3 24  6 43 20 26 49 12 23 40 32
 15 10 45 32 43 44 28 18 30  9 26 28 42  1 39 24 31  6 44 38 12 10 13 17
  5  7 17 23 29  3 46  1  5 14 22 29 30 25 43  2 39 13 23 28 49 45 23 40
  4 44 12  9 30 44 30  9 31 34 11  8  8  8 28 14 14  2 48 12 45 17  8 21
 21 16 44  3 30 35 44  5 28 44 43 42 48 48 48 21 25 33 26 10 28 49 10 18]


In [ ]:
print("Sum Of An Array")
print(np.sum(x))

Sum Of An Array
2990


In [ ]:
# numpy.mean()
# mean value is the average value
print("Mean Of An Array")
print(np.mean(x))

Mean Of An Array
24.916666666666668


In [ ]:
print("Min Of An Array")
print(np.min(x))
print("Max Of An Array")
print(np.max(x))

Min Of An Array
1
Max Of An Array
49


In [ ]:
# numpy.unique()
# return unique elements as a sorted array
a = np.array([1,2,3,11,4,10,9,12,5,6,1,4,3,2,5,6,7,8,9,2,3,4,5,7,1])
print(np.unique(a))

# 1 2 3 11 4 10 9 12 5 6 7 8

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [ ]:
a = np.array([1,2,3,11,4,10,9,12,5,6,1,4,3,2,5,6,7,8,9,2,3,4,5,7,1])
uv , i = np.unique(a,return_index=True)
print(uv)
print(i)
# return_index  --> it will print the index numbers

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[ 0  1  2  4  8  9 16 17  6  5  3  7]


In [ ]:
# argsort --> reorder the index numbers in a proper sequence
uv[np.argsort(i)]

array([ 1,  2,  3, 11,  4, 10,  9, 12,  5,  6,  7,  8])

In [ ]:
a = np.array([1,2,3,11,4,10,9,12,5,6,1,4,3,2,5,6,7,8,9,2,3,4,5,7,1])
uv , i = np.unique(a,return_index=True)
uv[np.argsort(i)]

array([ 1,  2,  3, 11,  4, 10,  9, 12,  5,  6,  7,  8])

In [ ]:
# arange()
print(np.arange(10))
print(np.arange(1,11))
print(np.arange(1,11,2))

[0 1 2 3 4 5 6 7 8 9]
[ 1  2  3  4  5  6  7  8  9 10]
[1 3 5 7 9]


In [ ]:
# Numpy Broadcasting
arr1 = np.array([16,24,26])
arr2 = np.array([13,22,19])

print(arr1+arr2)
print(arr1*arr2)

[29 46 45]
[208 528 494]


In [ ]:
arr1 = np.array([16,24,26,12]) # dekat sini ada extra shape, tiba tiba ada 12
arr2 = np.array([13,22,19]) # array tak sama shape
print(arr1+arr2)
# akan dapat error sebab tak sama Dimension
# error ni dipanggil broadcasting


ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [ ]:
# in which cases there will be no broadcasting error
# case 1 : when arrays are equal
# case 2 : if anyone of them is 1

arr1 = np.array([16,24,26])
arr2 = np.array([2])            # 2 2 2

print(arr1+arr2)